- name: "Disable use_tempaddr (all)"
  sysctl:
    name: net.ipv6.conf.all.use_tempaddr
    value: 0
    sysctl_file: /etc/sysctl.d/10-ipv6-privacy.conf

- name: "Disable use_tempaddr (default)"
  sysctl:
    name: net.ipv6.conf.default.use_tempaddr
    value: 0
    sysctl_file: /etc/sysctl.d/10-ipv6-privacy.conf

- name: "Disable router_solicitations"
  sysctl:
    name: net.ipv6.conf.default.router_solicitations
    value: 0
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

- name: "Disable accept_ra_rtr_pref"
  sysctl:
    name: net.ipv6.conf.default.accept_ra_rtr_pref
    value: 0
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

- name: "Disable accept_ra_pinfo"
  sysctl:
    name: net.ipv6.conf.default.accept_ra_pinfo
    value: 0
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

- name: "Disable accept_ra_defrtr"
  sysctl:
    name: net.ipv6.conf.default.accept_ra_defrtr
    value: 0
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

- name: "Disable accept_ra"
  sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: 0
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

- name: "Disable autoconf (default)"
  sysctl:
    name: net.ipv6.conf.default.autoconf
    value: 0
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

- name: "Disable autoconf (primary)"
  sysctl:
    name: net.ipv6.conf.{{ ansible_default_ipv6.interface }}.autoconf
    value: 0
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

- name: "Disable autoconf (all)"
  sysctl:
    name: net.ipv6.conf.all.autoconf
    value: 0
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

- name: "Disable dad_transmits"
  sysctl:
    name: net.ipv6.conf.default.dad_transmits
    value: 0
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

- name: "Set max_addresses"
  sysctl:
    name: net.ipv6.conf.default.max_addresses
    value: 1
    sysctl_file: /etc/sysctl.d/30-disable-accepting-ipv6-ra.conf

